### ISSUE TITLE
Schedule Page

### ISSUE THREAD

**Issue by kharioki** [rendercon/RenderconKe-app#1]
**Is your feature request related to a problem? Please describe.**
Implement a Schedule page with a list of scheduled sessions, and event day tabs

**Describe the solution you'd like**
Your solution should resemble the design below.
- create reusable SessionCard component
- render sessions in flatlist

![Schedule](https://github.com/user-attachments/assets/ccd94b1c-4d6a-4fd7-9916-6bc5ffe2bafe)

**Describe alternatives you've considered**

**Additional context**

**Comment by brianwachira** [comment]
@kharioki  let me work on this
