### ISSUE TITLE
Bookmarks Page

### ISSUE THREAD

**Issue by kharioki** [rendercon/RenderconKe-app#2]
**Is your feature request related to a problem? Please describe.**
Implement a Bookmarks page as shown in the design below

**Describe the solution you'd like**
Use the `<SessionCard />` component created in the first issue to render your bookmarked sessions.

![Bookmarked](https://github.com/user-attachments/assets/2050a265-41cf-4ca2-8660-640044de1576)

**Describe alternatives you've considered**

**Additional context**
Consider using Asyncstorage to store bookmarked sessions
- use the `useStoredState` hook that has been provided. Its a reusable way to store items in asyncstorage

**Comment by brianwachira** [comment]
@kharioki let me also work on this?

**Comment by kharioki** [comment]
Cool, I'll review tomorrow and finish the tasks that will be pending
