### ISSUE TITLE
Speakers Page

### ISSUE THREAD

**Issue by kharioki** [rendercon/RenderconKe-app#3]
**Is your feature request related to a problem? Please describe.**
Implement a speakers page as shown in the design below.

**Describe the solution you'd like**
- Create a reusable `<SpeakerCard />` component
- Use a FlatList to render a list of all speakers

![Speakers (1)](https://github.com/user-attachments/assets/f1537b8e-6169-4a99-b79b-86b497903f28)

**Describe alternatives you've considered**

**Additional context**

**Comment by cindykandie** [comment]
@cindykandie i will work on this
